general:
  artifacts:
    - "target/*/scoverage-report"
  branches:
    ignore:
      - /debug\/.*/

machine:
  java:
    version: oraclejdk8

dependencies:
  cache_directories:
    - "~/.sbt"
  override:
    - "sbt update"

test:
  override:
    - "sbt clean coverage test"
  post:
    - "sbt coverageAggregate coveralls"